repos:
- repo: local
  hooks:
#  - id: make-test
#    name: Running all unit/functional tests
#    entry: make test
#    language: system
  - id: make-isort
    name: Cleaning imports
    entry: make isort
    language: system
#  - id: make-lint
#    name: Linting the source code
#    entry: make lint
#    language: system
